language: ruby
rvm:
 - 2.2
 - jruby

deploy:
  - provider: script
  skip_cleanup: true
  script: "./abc.sh"
  on:
    branch: master
  
  - provider: script
  skip_cleanup: true
  script: "./def.sh"
  on:
    branch: release

