language: ruby
rvm: 
  - 2.2
  - jruby

deploy: 
  - 
    provider: script
    script: ./abc.sh
    skip_cleanup: true
    true: 
      branch: master
  - 
    provider: script
    script: ./def.sh
    skip_cleanup: true
    true: 
      branch: release
